In [2]:
# Import the needed libraries
import numpy as np

**72. How to swap two rows of an array?** 

In [3]:
swap_array = np.arange(25).reshape(5,5)
print(swap_array)

print('\n')

swap_array[[1,3]] = swap_array[[3,1]]
print(swap_array)





[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


[[ 0  1  2  3  4]
 [15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [20 21 22 23 24]]


**75. How to compute averages using a sliding window over an array?**

In [39]:
# I was't able to find a built-in function... had to work-around
data_array = np.arange(20).reshape(5,4)

print(data_array)

m,n = np.shape(data_array)
w_shape = (2,2)
def sliding_window_avg(arr, w_size : tuple, step = 1):
    AVG = []

    m, n = np.shape(arr)

    r, c = w_size

    for i in range(0,m - r + 1,step):
        for j in range(0,n - c + 1,step):
            w = data_array[i:i + r,j:j + c]
            avg = np.sum(w)/np.size(w)

    return np.array(AVG)

print(sliding_window_avg(data_array,w_shape,2))



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[]
