In [ ]:
# Import the needed libraries

**13. Create a 10x10 array with random values and find the minimum and maximum values**

In [17]:
import numpy as np

random_array = np.random.rand(10,10)

high = random_array.max()
low = random_array.min()

print(random_array)
print(f"Max: {high}")
print(f"Min: {low}")




[[0.80207932 0.19367623 0.58054928 0.46305598 0.81879301 0.22691252
  0.44004869 0.94294166 0.78969048 0.37843787]
 [0.26926579 0.53319838 0.22451627 0.29610294 0.41181762 0.58272456
  0.46199826 0.36939118 0.15510338 0.47383474]
 [0.97015045 0.63299257 0.96520573 0.42401056 0.73136383 0.3515136
  0.34923095 0.91882477 0.98603117 0.59291123]
 [0.55305482 0.60194699 0.72231623 0.24941605 0.97266988 0.59400797
  0.46931678 0.10796981 0.57618657 0.96753146]
 [0.64762012 0.19427989 0.95185651 0.73109907 0.6077859  0.97345952
  0.491596   0.29036018 0.22223838 0.07993551]
 [0.86780421 0.95862839 0.93283487 0.36838868 0.23911468 0.86211869
  0.03833051 0.0805289  0.69846358 0.57215226]
 [0.14699239 0.09140356 0.56549047 0.05788957 0.7869972  0.60878084
  0.81860614 0.32641833 0.49839507 0.12537411]
 [0.93638088 0.94983877 0.08017353 0.00540939 0.3284045  0.60414117
  0.84903987 0.8761413  0.51760824 0.59684626]
 [0.59354184 0.25712788 0.24925599 0.91814002 0.38164958 0.28724895
  0.30884927 

**15. Create a 2d array with 1 on the border and 0 inside**

In [26]:
zero_inside_array = np.ones((10,5))
zero_inside_array[1:-1,1:-1] = 0
print(zero_inside_array)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
