# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np


#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/alessio/anaconda3/envs/Strive/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/alessio/anaconda3/envs/Strive/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/alessio/anaconda3/envs/Strive/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/alessio/anaconda3/envs/Strive/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/alessio/anaconda3/envs/Strive/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/alessio/anaconda3/envs/Strive/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/alessio/anaconda3/envs/Strive/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/alessio/anaconda3/envs/Strive/inc

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆)

In [4]:
import numpy as np
n = np.zeros((4,4))
print("%d bytes" % (n.size * n.itemsize))

128 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array o

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
a = np.empty(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [34]:
a = np.arange(10,50)
a


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [35]:
a = np.arange(5)

b = np.flip(a)
b


array([4, 3, 2, 1, 0])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [36]:
M = np.arange(9).reshape(3,3)
print(M)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [37]:
arr = np.array([1, 2, 0, 0, 4, 0])
np.nonzero(arr)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [38]:
I = np.identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [40]:
R = np.random.rand(3,3,3)
print(R)

[[[0.12449402 0.10637416 0.43412959]
  [0.1439985  0.04674447 0.23780405]
  [0.95597341 0.9774761  0.43960283]]

 [[0.34898468 0.91965868 0.39989958]
  [0.22747327 0.91232238 0.53043717]
  [0.10001084 0.87755868 0.42267678]]

 [[0.44076149 0.93665541 0.83538311]
  [0.61455656 0.60095023 0.73087184]
  [0.739872   0.02527943 0.19615961]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [42]:
M = np.random.rand(10,10)
print(M)
print(f"Max: {M.max()} - Min: {M.min()}")


[[0.89089098 0.04449778 0.58830492 0.03325989 0.17411841 0.98594824
  0.6896149  0.74793244 0.40287538 0.91355869]
 [0.97432543 0.48244034 0.40119321 0.23062443 0.40761792 0.98279567
  0.19307337 0.39974209 0.09797403 0.56685652]
 [0.02779508 0.05401297 0.71736585 0.56555303 0.86115193 0.95363524
  0.54642317 0.52889406 0.27793286 0.0979326 ]
 [0.05245556 0.7854624  0.57078257 0.00814078 0.79796832 0.95540397
  0.90628462 0.86389709 0.39279205 0.12194414]
 [0.4936287  0.15650912 0.40172748 0.78128383 0.91520804 0.10869482
  0.31127693 0.69694604 0.8922903  0.50143667]
 [0.61194441 0.95130598 0.35948877 0.32941832 0.47447416 0.3077977
  0.94892748 0.28670818 0.03406531 0.11207368]
 [0.43443864 0.19142805 0.30852153 0.59241045 0.84016317 0.03913293
  0.48308726 0.6441429  0.58725805 0.90398897]
 [0.33640085 0.16093079 0.30666839 0.28675273 0.42278721 0.29917706
  0.62665441 0.56580376 0.77410061 0.10500569]
 [0.58379814 0.7381052  0.28596263 0.68096288 0.38025904 0.05233117
  0.03294677 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [43]:
m = np.random.randint(1,30,30).mean()

print(m)


13.5


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [45]:
A = np.ones((5,6))

A[1:-1,1:-1] = 0

print(A)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [55]:
C = np.arange(12).reshape(3,4)

C = np.pad(C, pad_width=1, mode='constant', constant_values=0)
print(C)

[[ 0  0  0  0  0  0]
 [ 0  0  1  2  3  0]
 [ 0  4  5  6  7  0]
 [ 0  8  9 10 11  0]
 [ 0  0  0  0  0  0]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [57]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
0.3 == 3 * 0.1


nan
False
False
nan
True


False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [3]:
A = np.diag(1+np.arange(4), k = -1)
print (A)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [60]:
np.indices((8,8)).sum(axis=0) % 2

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [4]:
print (np.unravel_index(100, (6,7,8)))


(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [7]:
array= np.array([[0,1], [1,0]])
Z = np.tile(array,(4,4))
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [8]:
x= np.random.random((3,3))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)


Original Array:
[[0.39137785 0.95572163 0.65323132]
 [0.30487262 0.96360772 0.98939555]
 [0.8660417  0.04816279 0.68642015]]
After normalization:
[[0.36464419 0.9642236  0.64284686]
 [0.27273788 0.97260206 1.        ]
 [0.86894437 0.         0.67810789]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [13]:
rgba = np.dtype('4u1')
type(rgba)


numpy.dtype

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [14]:
A = np.arange(15).reshape(5,3)
B = np.arange(6).reshape(3,2)

print(A@B)


[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [18]:
a = np.random.randint(0,10,20)
print(a)
c=np.where((a>2) & (a<9) ,a*-1,a)
print(c)

[4 5 8 4 6 0 2 9 1 5 3 7 4 8 5 6 1 1 1 0]
[-4 -5 -8 -4 -6  0  2  9  1 -5 -3 -7 -4 -8 -5 -6  1  1  1  0]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [20]:
9
10

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [21]:
Z = np.arange(10)
print(Z)
A.all()

[0 1 2 3 4 5 6 7 8 9]


False

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [25]:
# 1. nan
# 2. nan

print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))


nan
0
[-9.22337204e+18]


<ipython-input-25-5cc6c438fe56>:4: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-25-5cc6c438fe56>:5: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [23]:
a = np.random.rand(10)*10

print(np.round(a,0))


[ 5.  0.  4.  3.  6. 10. 10.  6.  1.  5.]


#### 30. How to find common values between two arrays? (★☆☆)

In [26]:
A = np.array([1, 5, 4, 6, 9])
B = np.array([2, 6, 3, 9, 5])

np.intersect1d(A, B)

array([5, 6, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
#numpy.seterr()

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [28]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))

#no, I's False


nan
1j


<ipython-input-28-71752a739b85>:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [29]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2021-03-23
Today:  2021-03-24
Tomorrow:  2021-03-25


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [33]:
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
dates

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [36]:
A = np.array([1, 5, 4, 6, 9])
B = np.array([2, 6, 3, 9, 5])

C = ((A + B)*(-A/2))
C

array([ -1.5, -27.5, -14. , -45. , -63. ])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [48]:
Z = np.random.rand(3,4) + np.random.randint(0,9,(3,4))
print(Z)
print('\n')
E = Z//1
print(E)
print('\n')
F = np.floor(Z)
print(F)
print('\n')
G = np.trunc(Z)
print(G)
print('\n')
H = np.fix(Z)
print(H)
print('\n')
L = np.ceil(Z) - 1
print(L)



[[5.88791983 4.70653019 0.66920218 5.88255766]
 [1.44270238 7.16803608 6.26561436 8.38566667]
 [7.57333175 6.66873879 5.33335674 6.45478599]]


[[5. 4. 0. 5.]
 [1. 7. 6. 8.]
 [7. 6. 5. 6.]]


[[5. 4. 0. 5.]
 [1. 7. 6. 8.]
 [7. 6. 5. 6.]]


[[5. 4. 0. 5.]
 [1. 7. 6. 8.]
 [7. 6. 5. 6.]]


[[5. 4. 0. 5.]
 [1. 7. 6. 8.]
 [7. 6. 5. 6.]]


[[5. 4. 0. 5.]
 [1. 7. 6. 8.]
 [7. 6. 5. 6.]]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [49]:
x = np.zeros((5,5))
print("Original array:")
print(x)
print("Row values ranging from 0 to 4.")
x += np.arange(5)
print(x)


Original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4.
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [51]:
RAND = np.random.randint(10,19,(5,6))
RAND
# Have to take another look


array([[12, 14, 18, 11, 13, 12],
       [16, 13, 13, 17, 18, 16],
       [15, 10, 15, 14, 12, 17],
       [12, 15, 11, 18, 14, 14],
       [11, 13, 16, 14, 14, 18]])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [53]:
A = np.random.rand(10)
A

array([0.7213965 , 0.42903109, 0.79581905, 0.1356971 , 0.24296282,
       0.6100118 , 0.47294131, 0.709581  , 0.45958167, 0.28593607])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [13]:
random = sorted(np.random.randint(0,10,10))
print(random)

[0, 0, 0, 2, 4, 6, 7, 8, 9, 9]


#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [26]:
a = np.random.randint(0,20,30)
b = np.random.randint(0,20,30)

np.allclose(a, b)


False

#### 43. Make an array immutable (read-only) (★★☆)

In [30]:
a = np.arange(10)
a.flags.writeable = False
a[0] = 10

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [32]:
cartesian = np.random.randint(0,10,(10,2))


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [38]:
a = np.random.rand(10)
print(a)

max = a[np.argmax(a)]

print(max)


[0.66892325 0.39686514 0.32287591 0.24755913 0.52250217 0.52770678
 0.29907908 0.14940777 0.91380555 0.67387562]
0.9138055481457446


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [33]:
Z = np.random.random((3,2))
#print(Z)
X,Y = np.atleast_2d(Z[:,0]), np.atleast_2d(Z[:,1])  # Scalar and 1-dimensional inputs are converted to 2-dimensional arrays,
                                                    # whilst higher-dimensional inputs are preserved
print("X-X.T",X - X.T)
print("Y-Y.T",Y - Y.T)                              #x1,y1.      x2,y2.

print(X - X.T)



X-X.T [[ 0.          0.60477817  0.32669552]
 [-0.60477817  0.         -0.27808266]
 [-0.32669552  0.27808266  0.        ]]
Y-Y.T [[ 0.          0.52280571  0.20876922]
 [-0.52280571  0.         -0.3140365 ]
 [-0.20876922  0.3140365   0.        ]]
[[ 0.          0.60477817  0.32669552]
 [-0.60477817  0.         -0.27808266]
 [-0.32669552  0.27808266  0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)